FROM openjdk:11 AS VPro_Build
LABEL "Project"="VProfile"
LABEL "Author"="Skillet - modified from Imran"
RUN apt update && apt install maven -y
RUN git clone https://github.com/william-t-lodge/vprofile-project.git
RUN cd vprofile-project && git checkout containers && mvn install

FROM tomcat:9-jre11
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=VPro_Build vprofile-project/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]